MySQL:

  Host: '18.229.96.83'
  DataBase: 's10124_Naomeche'
  Username: 'u10124_TzFzHg36Zb'
  Password: 'WJNjl=f2b5A9B77KAx!ZE@lV'
  Port: 3306

Discord:

  Token: ''
  Status: ''

Servidor:

  ##Caso queira ativar/desativar o Sistema de Login troque essa opção##
  LoginSystem: true

  ##Caso queira que os jogadores Premiums(Originais) se loguem automaticamente ative essa opção##
  ##OBS.: Caso troque essa opção delete o arquivo "LoginDataBase.db" da pasta do plugin, para ficar livre de bugs##
  PremiumAutoLogin: true


  ##Caso queira ativar/desativar o Sistema de Bans troque essa opção##
  BanSystem: true

  NomeDoServidor: '&b&lKit&f&lPvP'

  Site: 'www.kitpvp.com.br'


Messages:
  ##A legenda abaixo só irá servir para as menssagens do Ban, TempBan, Mute, TempMute, Kick##
  ##{breakline} - Quebra de Linha##
  ##{staff} - Mostra quem baniu/mutou/kickou o jogador##
  ##{time} - Mostra quanto tempo ainda falta para terminar o ban/mute##
  ##{reason} - Mostra o motivo do ban/mute/kick##

  Ban: '&cVocê foi banido permanentemente.{breakline}
  &cPor: {staff}{breakline}
  &cMotivo: {reason}{breakline}
  {breakline}
  &cBanido injustamente? Contante-nos em &bwww.kitpvp.com.br/appeal.{breakline}
  &cCompre unban em &bwww.kitpvp.com.br/unban'

  TempBan: '&cVocê foi banido temporariamente.{breakline}
  &cPor: {staff}{breakline}
  &cExpira em: {time}{breakline}
  Motivo: {reason}{breakline}
  {breakline}
  &cBanido injustamente? Contante-nos em &bwww.kitpvp.com.br/appeal.{breakline}
  &cCompre unmute em &bwww.kitpvp.com.br/unmute'

  Mute: '&cVocê foi mutado permanentemente.{breakline}
  &cPor: {staff}{breakline}
  &cMotivo: {reason}{breakline}
  &cCompre unmute em &bwww.kitpvp.com.br/unmute'

  TempMute: '&cVocê foi mutado temporariamente.{breakline}
  &cPor: {staff}{breakline}
  &cMotivo: {reason}{breakline}
  &cExpira em: {time}.'

  Kick: '&cVocê foi expulso do servidor.{breakline}
  &cPor: {staff}{breakline}
  Motivo: {reason}'

  NoPermission: '&c&lPermission &fVocê não possui permissão.'
